EzIRFront/Components/CoCauSoHuu/CoCauSoHuuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EzIRFront.Components.CoCauSoHuu
{
    public class CoCauSoHuuViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return this.View();
        }
    }

}

EzIRFront/Components/CoPhieu/DoThiKyThuatViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EzIRFront.Components.CoPhieu
{
    public class DoThiKyThuatViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return this.View();

        }
    }
}

EzIRFront/Components/CoPhieu/LichSuGiaoDichViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace EzIRFront.Components.CoPhieu
{
    public class LichSuGiaoDichViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return this.View();
        }
    }
}

EzIRFront/Components/CoPhieu/LichSuTangVonTraCoTucViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EzIRFront.Components.CoPhieu
{
    public class LichSuTangVonTraCoTucViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return this.View();
        }
    }
}

EzIRFront/Components/KinhDoanh/NangLucQuanLyViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EzIRFront.Components.KinhDoanh
{
    public class NangLucQuanLyViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return this.View();
        }
    }
}

EzIRFront/Components/KinhDoanh/PhanTichSWOTViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EzIRFront.Components.KinhDoanh
{
    public class PhanTichSWOTViewComponent: ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return this.View();
        }
    }
}

EzIRFront/Components/KinhDoanh/ThiTruongKHDTViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EzIRFront.Components.KinhDoanh
{
    public class ThiTruongKHDTViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return this.View();
        }
    }
}

EzIRFront/Components/KinhDoanh/ThongTinDuAnDauTuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EzIRFront.Components.KinhDoanh
{
    public class ThongTinDuAnDauTuViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return this.View();
        }
    }
}

EzIRFront/Components/KinhDoanh/TrinhDoCongNgheViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EzIRFront.Components.KinhDoanh
{
    public class TrinhDoCongNgheViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return this.View();
        }
    }
}

EzIRFront/Components/KinhDoanh/ViTheDoanhNghiepViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EzIRFront.Components.KinhDoanh
{
    public class ViTheDoanhNghiepViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return this.View();
        }
    }
}

EzIRFront/Components/LuuTru/LuuTruTinDoanhNghiepViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EzIRFront.Components.LuuTru
{
    public class LuuTruTinDoanhNghiepViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return this.View();
        }
    }
}

EzIRFront/Components/LuuTru/LuuTruTinTuSoVaVSDViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EzIRFront.Components.LuuTru
{
    public class LuuTruTinTuSoVaVSDViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return this.View();
        }
    }
}

EzIRFront/Components/PhanTichFPTS/PhanTichFPTSViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EzIRFront.Components.PhanTichFPTS
{
    public class PhanTichFPTSViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return this.View();
        }
    }
}

EzIRFront/Components/TaiChinh/CanDoiKeToanViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EzIRFront.Components.TaiChinh
{
    public class CanDoiKeToanViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return this.View();
        }
    }
}

EzIRFront/Components/TaiChinh/HeSoTaiChinhViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EzIRFront.Components.TaiChinh
{
    public class HeSoTaiChinhViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return this.View();
        }
    }
}

EzIRFront/Components/TaiChinh/KeHoachTaiChinhViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EzIRFront.Components.TaiChinh
{
    public class KeHoachTaiChinhViewComponent : ViewComponent
    {

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return this.View();
        }
    }
}

EzIRFront/Components/TaiChinh/KetQuaHoatDongKinhDoanhViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace EzIRFront.Components.TaiChinh
{
    public class KetQuaHoatDongKinhDoanhViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return this.View();
        }
    }
}

EzIRFront/Components/TaiChinh/LuuChuyenTienTeDCFViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace EzIRFront.Components.TaiChinh
{
    public class LuuChuyenTienTeDCFViewComponent: ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return this.View();
        }
    }
}

EzIRFront/Controllers/ThongTinDoanhNghiepController.cs
using CommonLib.Interfaces;
using CommonLib.Interfaces.Logger;
using CoreLib.Commons;
using CoreLib.Configs;
using CoreLib.Entities;
using CoreLib.Entities.ViewModels;
using CoreLib.Services;
using CoreLib.SharedKernel;
using EzIRFront.DataAccess;

//using EzIRFront.Commons;
using EzIRFront.Models;
using EzIRFront.Models.ModelViews;
using EzIRFront.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Localization;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;


namespace EzIRFront.Controllers
{
    public class ThongTinDoanhNghiepController : Controller
    {
        private readonly IConfiguration _config;
        //private readonly ILogger<HomeController> _logger;
        private IMemoryCache _cache;
        private IAppLogger _appLogger;
        private static readonly HttpClient client = new HttpClient();
        private HttpClient client_KLGD;
        string baseUri = "";
        private readonly ISerilogProvider _serilogProvider;
        //private readonly IValidateApi _validateApi;
        private static WebApiConfigs _WebApiConfig = new WebApiConfigs();
        string tintucUri = "";
        string tinTucLink = "";
        string tinTucDNLink = "";
        string Imgbm = "";
        string fileLink = "";
        string ImgbmLogo = "";
        string CkeditorImgUrl = "";
        string Gia = "";
        string priceUri = "";
        string UrlFile = "";
        private readonly IHtmlLocalizer<SharedResource> _localizer;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ICommon _common;
        private readonly IExportExcel _excel;
        private string _api_KLGDTT;
        private string _api_BETA;
        string language = "vn";
        string cookieValue = "vn";
        string protocol = "";

        CultureInfo provider = CultureInfo.InvariantCulture;

        public ThongTinDoanhNghiepController(IHttpContextAccessor httpContextAccessor, IMemoryCache cache, IConfiguration config, IAppLogger appLogger, ISerilogProvider serilogProvider, IHtmlLocalizer<SharedResource> localizer, ICommon common, IExportExcel excel)

        {
            _cache = cache;
            _config = config;
            _appLogger = appLogger;
            this._serilogProvider = serilogProvider;
            config.GetSection("API").Bind(_WebApiConfig);
            baseUri = _WebApiConfig.BASE_URL;
            tintucUri = _WebApiConfig.API_TinTuc;
            priceUri = _WebApiConfig.API_PRICE;
            _api_KLGDTT = _WebApiConfig.API_KLGDTT;
            _api_BETA = _WebApiConfig.API_BETA;
            UrlFile = _config.GetSection("UrlFile").Value;
            _localizer = localizer;
            tinTucDNLink = "&pageSize=8&selectedPage=1&cbtt=1&from=01-01-1970&to=01-01-3000&newsType=1";
            tinTucLink = "&pageSize=8&selectedPage=1&cbtt=0&from=01-01-1970&to=01-01-3000&newsType=1";
            Imgbm = _config.GetSection("UrlImg").Value;
            ImgbmLogo = _config.GetSection("UrlImgLogo").Value;
            fileLink = _config.GetSection("UrlTPLD").Value;
            protocol = _config.GetSection("ProtocolStatus").Value;
            CkeditorImgUrl = _config.GetSection("CkeditorImgUrl").Value;
            Gia = "&fromDate=2020-1-1&toDate=2021-1-1";
            _httpContextAccessor = httpContextAccessor;
            _common = common;
            _excel = excel;
        }

        public IActionResult Index()
        {

            language = CommonLib.CommonUtil.ReturnLanguge(_httpContextAccessor.HttpContext.Request.QueryString.ToString());
            cookieValue = CommonLib.CommonUtil.ReturnLanguge(_httpContextAccessor.HttpContext.Request.QueryString.ToString());
            TempData["tintucLanguage"] = language;
            ViewBag.Protocol = protocol;
            ViewBag.CookiesVaule = cookieValue;
            return View();
        }
        ////api/companyinfo/listcompany
        /// <summary>
        /// Lấy thông tin mã chứng khoán, công ty
        /// </summary>
        /// <returns></returns>
        /// 
        [HttpGet]
        public async Task<IActionResult> GetStockCodeThongTinDN()
        {

            try
            {
                //   string language = CommonLib.CommonUtil.ReturnLanguge(_httpContextAccessor.HttpContext.Request.QueryString.ToString());
                language = CommonLib.CommonUtil.ReturnLanguge(_httpContextAccessor.HttpContext.Request.QueryString.ToString());
                if (language != null)
                {
                    language = language.Replace("en-US", "EN");
                }

                var requestUri = $"{baseUri + WebApiConfigs.Link_WebApi_StockCode + "?Language=" + language}";

                var response = await HttpRequestFactory.Get(requestUri);

                this._serilogProvider.Logger.Debug($"Status:" + response.StatusCode.ToString());  // Ghi log hệ thống

                var Data_Company = response.Content.ReadAsStringAsync().Result;

                var jObj = JsonConvert.DeserializeObject(Data_Company) as JObject;

                var jArr = jObj.GetValue("table");

                var table = jArr.ToObject<List<CompanyService>>();

                var data = new List<object>();

                table.ForEach(x => data.Add(new { astock_CODE = x.astock_CODE, nameSearch = $"{x.astock_CODE} - {x.astockname}" }));

                return Json(data);

            }

            catch (Exception ex)
            {
                _appLogger.ErrorLogger.LogError(ex);
                return Json(new CResponseMessage { Code = -3, Message = "InternalServerError" });
            }

        }


        /// <summary>
        /// Load lại thông tin trag EzIR thông tin doanh nghiệp theo mã chứng khoán được search
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> SelectStockCode(ThongTinViewModel thongTinViewModel)
        {
            cookieValue = CommonLib.CommonUtil.ReturnLanguge(_httpContextAccessor.HttpContext.Request.QueryString.ToString());
            if (cookieValue.Contains("?culture=en-US"))
                cookieValue = "?culture=en-US";
            else
                cookieValue = "";
            return Redirect("/ThongTinDoanhNghiep/" + thongTinViewModel.astocK_CODE + cookieValue);


        }

        public IActionResult ThongTinChung()
        {
            cookieValue = ViewBag.CookiesVaule;
            ViewBag.Protocol = protocol;
            //   cookieValue = CommonLib.CommonUtil.ReturnLanguge(_httpContextAccessor.HttpContext.Request.QueryString.ToString());
            ViewBag.Language = cookieValue;
            ViewBag.Imgbm = Imgbm + "/";
            ViewBag.ImgbmLogo = ImgbmLogo + "/";
            ViewBag.CkeditorImgUrl = CkeditorImgUrl;
            return this.ViewComponent("Thongtinchung");
        }


        public IActionResult Chart()
        {
            //   cookieValue = CommonLib.CommonUtil.ReturnLanguge(_httpContextAccessor.HttpContext.Request.QueryString.ToString());
            //ViewBag.Language = cookieValue;
            return View();
        }

        /// <summary>
        /// Lấy khối lượng giao dịch thỏa thuận
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> GetKhoiLuongGiaoDichThoaThuan()
        {
            try
            {

                //var fromDate = DateTime.Now.ToString("yyyy-MM-dd");
                //var toDate = DateTime.Now.ToString("yyyy-MM-dd");


                //var requestUri = $"{baseUri + WebApiConfigs.Link_WebApi_Listpricehistory + "?fromDate=" + fromDate + "&toDate=" + toDate + "&stockCode=" + stock_code }";

                //var response = await HttpRequestFactory.Get(requestUri);

                //this._serilogProvider.Logger.Debug($"Status:" + response.StatusCode.ToString());  // Ghi log hệ thống

                ////cResponseMessage = JsonConvert.DeserializeObject<CResponseMessage>(response.Content.ReadAsStringAsync().Result);

                //var Data_Banner = response.Content.ReadAsStringAsync().Result;

                //var jObj = JsonConvert.DeserializeObject(Data_Banner) as JObject;

                //var jArr = jObj.GetValue("table");

                //var table = jArr.ToObject<List<ThongTinViewModel>>();

                //return Json(table);

                string klgdtt = _api_KLGDTT;
                HttpResponseMessage res = await client.GetAsync(klgdtt);
                if (res.IsSuccessStatusCode)
                {
                    var data = await res.Content.ReadAsStringAsync();
                    var jObj = JsonConvert.DeserializeObject(data) as JObject;
                    var dataKLGDTT = jObj.ToString();
                    return Ok(dataKLGDTT);
                }
                return Ok();
            }

            catch (Exception ex)
            {
                _appLogger.ErrorLogger.LogError(ex);
                return Json(new CResponseMessage { Code = -3, Message = "InternalServerError" });
            }
        }

        /// <summary>
        /// Lấy Beta
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> CalBetaStock(string stock_code, DateTime fromDate, DateTime toDate)
        {
            string beta = _api_BETA + "?fDate=" + fromDate.ToString("MM-dd-yyyy") + "&tDate=" + toDate.ToString("MM-dd-yyyy") + "&stockCode=" + stock_code;
            HttpResponseMessage res = await client.GetAsync(beta); 
            if (res.IsSuccessStatusCode)
            {

EzIRFront/Views/Shared/Components/TamNhinChienLuoc/Default.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@using Microsoft.AspNetCore.Http;
@inject IHtmlLocalizer<SharedResource> Localizer;
@using Microsoft.AspNetCore.Localization
@{
    var img = ViewBag.Imgbm;
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var language = requestCulture.RequestCulture.UICulture.Name;
}

<div class="k-content	k-grid__item k-grid__item--fluid k-grid k-grid--hor DaiHoiform"
     id="k_content">


    <div id="content">

        <!-- Begin Page Content -->
        <div class="container-fluid">

            <!-- Page Heading -->
            <!-- Content Row -->
            <!-- Content Row -->
            <!-- Content Row -->
            <div id="tamnhin" class="row">
                
            </div>
            
            <div id="chienluoc" class="row">

            </div>
            

        </div>
        <!-- /.container-fluid -->

    </div>

    <!-- End of Main Content -->


</div>
<div id="loading"></div>
<script>
     $(document).ready(function () {
            //console.log(stockcode);
         var ThongTin = function () {

             this.init = function () {
                loadData();
                loadchienluoc();
            }
             //tầm nhìn
             var loadData = function () {
                $('#loading').addClass('loading');

                var cpnyId = $("#cpnyid").val();
                        $.ajax({
                            url: '@Url.Action("GetTamNhin", "ThongTinDoanhNghiep")',
                            method: 'GET',
                            dataType: 'json',
                            data: { cpnyID: cpnyId} ,
                            success: function (data) {
                                $('#loading').removeClass('loading');

                                 var lang = ReturnLanguage();

                                let html = '';
                                for (const item of data) {
                                    if (lang == "vi-VN" || lang == '') {
                                        if (item.alanguage == "VN") {
                                            html += `
                                            <div class="contentt">
                                                                <p>@Localizer["Tam_nhin"].Value</p>
                                                            </div>

                                                            <div class="tamnhin" style="width:100%;overflow: auto;">
                                                            ${item.acontent.replaceAll('Images/Inforsheet', '@img/Images/Inforsheet')}
                                                            </div>
                                            `;
                                        }
                                    } else {
                                        if (item.alanguage == "US") {
                                           html += `
                                            <div class="contentt">
                                                                <p>@Localizer["Tam_nhin"].Value</p>
                                                            </div>

                                                            <div class="tamnhin" style="width:100%;overflow: auto;">
                                                            ${item.acontent.replaceAll('Images/Inforsheet', '@img/Images/Inforsheet')}
                                                            </div>
                                            `;
                                        }
                                    }


                                }

                                $('#tamnhin').append(html);
                            },
                            error: function (err) {
                                $('#loading').removeClass('loading');
                               // console.log(err);
                            }
                        });
             }
             //chiến lược
             var loadchienluoc = function () {
                 $('#loading').addClass('loading');
                        var cpnyId = $("#cpnyid").val();
                          $.ajax({
                            url: '@Url.Action("GetChienLuoc", "ThongTinDoanhNghiep")',
                            method: 'GET',
                            dataType: 'json',
                              data: { cpnyID: cpnyId} ,
                            success: function (data) {
                            console.log(data);
                                $('#loading').removeClass('loading');
                                  var lang = ReturnLanguage();
                                let html = '';
                                for (const item of data) {
                                    if (lang == "vi-VN" || lang == '') {
                                        if (item.alanguage == "VN") {
                                            html += `<div class="contentt">
                                                    <p>@Localizer["Chien_luoc"].Value</p>
                                                </div>

                                                <div class="chienluoc" style="width:100%;">
                                                     ${item.acontent.replaceAll('Images/Inforsheet', '@img/Images/Inforsheet')}

                                                </div>`;
                                                                            }
                                    } else {
                                        if (item.alanguage == "US") {
                                            html += `<div class="contentt">
                                                    <p>@Localizer["Chien_luoc"].Value</p>
                                                </div>

                                                <div class="chienluoc" style="width:100%;" >
                                                     ${item.acontent.replaceAll('Images/Inforsheet', '@img/Images/Inforsheet')}

                                                </div>`;
                                        }
                                    }
                                }

                            $('#chienluoc').append(html);
                        },
                              error: function (err) {
                                  $('#loading').removeClass('loading');
                                 // console.log(err);
                        }
                    });
             }
        }
         var thongTin = new ThongTin();
         thongTin.init();
    });
</script>